---
collections:

  - name: https://github.com/ansible-collections/ansible.posix
    type: git
  - name: https://github.com/ansible-collections/amazon.aws
    type: git
  - name: https://github.com/ansible-collections/community.aws
    type: git
  - name: https://github.com/ansible-collections/community.docker
    type: git
  - name: https://github.com/ansible-collections/google.cloud
    type: git
  - name: https://github.com/containers/ansible-podman-collections
    type: git
