---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Bootstrap python for Ansible
      ansible.builtin.package:
        name: python3
        state: present
      become: true
      changed_when: false
      when: ansible_system == "Linux"
